### ISSUE TITLE
add dependency updater to org: renovate/dependabot

### ISSUE THREAD

**Issue by oscard0m** [octoherd/cli#15]

**Comment by gr2m** [comment]
Would you like to set it up? I can invite you to the org as owner. I’d go with renovate

**Comment by oscard0m** [comment]
Sure!

**Comment by gr2m** [comment]
Okay, shall we use the same configuration as we do in @octokit?
https://github.com/octokit/.github/blob/master/renovate.json

We should remove the labels setting, or add the same labels as we do in @octokit to our repositories. Which I'd love but we can do that later, one thing at a time.

I've invited you as owner to https://github.com/octoherd, you should see the invitation on https://github.com/octoherd

**Comment by gr2m** [comment]
I've setup renovate
