### ISSUE TITLE
To add support repository name patterns

### ISSUE THREAD

**Issue by oscard0m** [octoherd/cli#20]
e.g. not `octoherd/script-*-something-*`. 

> Eventually we should probably rely on a dedicated pattern matching library, I'd suggest to keep it simple until the need for more complexity arises. Let me know what you think

_Originally posted by @gr2m in https://github.com/octoherd/cli/pull/18#discussion_r587937226_

**Comment by gr2m** [comment]
done via https://github.com/octoherd/cli/pull/18 🎉
