### ISSUE TITLE
set log context for script

### ISSUE THREAD

**Issue by gr2m** [octoherd/cli#21]
follow up https://github.com/oscard0m/octoherd-script-watch-unwatch-or-ignore/pull/1#discussion_r588973902

Basically before 

https://github.com/octoherd/cli/blob/309a72c7141115805278cfd99a0b4ee7d4b4c092/index.js#L101

Add a line

```js
octokit.log.setContext({
  repository: {
    id,
    owner,
    name
  }
})
```

**Comment by oscard0m** [comment]
Opening PR, but blocked by this issue:
https://github.com/octoherd/octokit/issues/6
