### ISSUE TITLE
Owner with upper-case fails

### ISSUE THREAD

**Issue by oscard0m** [octoherd/cli#41]
![image](https://user-images.githubusercontent.com/2574275/117966823-a5653500-b324-11eb-8eb1-cd013498dacb.png)

🆚 

![image](https://user-images.githubusercontent.com/2574275/117966874-b57d1480-b324-11eb-9570-caf4512ab91d.png)

The example is a private repository but I can try to find (or create) an owner starting with capital letter to show.

**Comment by oscard0m** [comment]
@gr2m let me know if this is an expected behaviour (so we improve the message for users) or we should support `<Owner>` and `<owner>`

**Comment by gr2m** [comment]
great catch! We should support both, repository and owner names are case-insensitive
