### ISSUE TITLE
Support `--version` parameter

### ISSUE THREAD

**Issue by gr2m** [octoherd/cli#56]
When `--version` is set on a script, then `node` takes over and returns the output of `node --version`

**Comment by stefanbuck** [comment]
Looks like this has been resolved by now

<img width="713" alt="image" src="https://user-images.githubusercontent.com/1393946/197622777-75ee50df-9eb9-4caa-9833-11155744bb99.png">

**Comment by gr2m** [comment]
it is indeed, thanks Stefan!
