### ISSUE TITLE
Add support for ignoring specific repositories

### ISSUE THREAD

**Issue by stefanbuck** [octoherd/cli#95]
When using `-R repo-owner/*` octoherd will return all repositories within `repo-owner`. In certain circumstances you might want to ignore one or more repositories. 

First I was thinking about another argument like `--octoherd-ingore-repos`, but this would require adding another prompt when using the interactive mode. Another idea was using a regex, but this can get quite complicated  I think(from a user point of view)

Which leads to my preferred options, negating the existing repo argument by adding a leading exclamation mark like `-R !repo-owner/repo-to-ignore`. A full example would look like this

```
npx @octoherd/script-hello-world \
  --octoherd-token 0123456789012345678901234567890123456789 \
  -R 'repo-owner/*' \
  -R !repo-owner/repo-to-ignore`
  -R !repo-owner/another-repo-to-ignore`
```

This should (in theory) work quite well with the interactive mode as well.

```
Enter repositories: repo-owner/*, !repo-owner/repo-to-ignore
```

**Comment by gr2m** [comment]
I'd be open to that
